version: '3.1'
services:
    nginx:
       image: nginx
       restart: always
       ports:
         - "19999:80"
       privileged: true
    ab-test:
       image: siangyeh8818/iperf-client:v3
       restart: always
       privileged: true
