---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iperf-client
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      containers:
      - name: iperf-client
        image: siangyeh8818/iperf-client:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5201
        volumeMounts:
        - name: time
          mountPath: /etc/localtime
      volumes:
      - name: time
        hostPath:
          path: /etc/localtime
      nodeSelector:
        kubernetes.io/hostname: "worker02"
---
apiVersion: v1
kind: Service
metadata:
 name: iperf-client
spec:
  ports:
  - port: 5201
    targetPort: 5201
  selector:
    app: iperf-client
